version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: HotelDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elephant16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: myapp-api
    depends_on:
      - postgres
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

volumes:
  postgres_data: