// <auto-generated />
using System;
using HotelSystemIndustry.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelSystemIndustry.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260316155457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventHallEventReservation", b =>
                {
                    b.Property<Guid>("EventHallsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventReservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("EventHallsId", "EventReservationsId");

                    b.HasIndex("EventReservationsId");

                    b.ToTable("EventHallEventReservation");
                });

            modelBuilder.Entity("EventReservationRoom", b =>
                {
                    b.Property<Guid>("EventReservationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uuid");

                    b.HasKey("EventReservationsId", "RoomsId");

                    b.HasIndex("RoomsId");

                    b.ToTable("EventReservationRoom");
                });

            modelBuilder.Entity("GuestReservation", b =>
                {
                    b.Property<Guid>("GuestsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GuestsId", "ReservationsId");

                    b.HasIndex("ReservationsId");

                    b.ToTable("GuestReservation");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Address", b =>
                {
                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.HasKey("Street", "City", "PostalCode");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.EmployeeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmployeeProfiles");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EquipmentInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventHallId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventReservationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReservationPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EventHallId");

                    b.HasIndex("EventReservationId");

                    b.ToTable("EquipmentInstances");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EquipmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventHall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("NumMaxGuests")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ReservationPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("EventHalls");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<long>("NumGuests")
                        .HasColumnType("bigint");

                    b.Property<long>("NumRequiredStaff")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("EventReservations");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventReservationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("EventReservationStatuses");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.EmployeeShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeShifts");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.HousekeepingSupply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumRequiredQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityInStock")
                        .HasColumnType("numeric");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HousekeepingSupplies");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.LostAndFoundItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FoundByEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoundByEmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("LostAndFoundItems");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("MaintenanceRequests");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.RoomCleaning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomCleanings");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.ArticleInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Count")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("StorageId");

                    b.ToTable("KitchenArticleInstances");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("KitchenArticles");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenArticleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("KitchenArticleTypes");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ContainsAlcohol")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EventReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EventReservationId");

                    b.HasIndex("OrderId");

                    b.ToTable("KitchenProducts");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid>("OutcomeProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OutcomeProductId");

                    b.ToTable("KitchenRecipes");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenRecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Count")
                        .HasColumnType("numeric");

                    b.HasKey("RecipeId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("KitchenRecipeIngredients");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryDestination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("KitchenOrders");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.OrderType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("KitchenOrderTypes");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("KitchenStorages");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Raport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Raports");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.RaportPayment", b =>
                {
                    b.Property<Guid>("RaportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("RaportId", "PaymentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("RaportPayments");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Recreation.RecreationBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("GuestId");

                    b.ToTable("RecreationBookings");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Recreation.RecreationFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("MaxCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("RecreationFacilities");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("NumberOfOvernightStays")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecialWishes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePricePerNight")
                        .HasColumnType("numeric");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Renovation")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopPointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopPointId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ContainsAlcohol")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.SaleItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MagazineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MagazineId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("SaleItemInstances");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.SaleItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("SaleItemTypes");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.ShopMagazine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ShopMagazines");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.ShopPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ShopPoints");
                });

            modelBuilder.Entity("SupplyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountUsed")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RoomCleaningId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomCleaningId");

                    b.HasIndex("SupplyId");

                    b.ToTable("SupplyUsages");
                });

            modelBuilder.Entity("EventHallEventReservation", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Events.EventHall", null)
                        .WithMany()
                        .HasForeignKey("EventHallsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Events.EventReservation", null)
                        .WithMany()
                        .HasForeignKey("EventReservationsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EventReservationRoom", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Events.EventReservation", null)
                        .WithMany()
                        .HasForeignKey("EventReservationsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GuestReservation", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Address", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Hotel", "Hotel")
                        .WithOne("Address")
                        .HasForeignKey("HotelSystemIndustry.Models.Address", "HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.Equipment", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Events.EquipmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EquipmentInstance", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Events.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Events.EventHall", null)
                        .WithMany("Equipment")
                        .HasForeignKey("EventHallId");

                    b.HasOne("HotelSystemIndustry.Models.Events.EventReservation", null)
                        .WithMany("Equipment")
                        .HasForeignKey("EventReservationId");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventReservation", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Events.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Events.EventReservationStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.EmployeeShift", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.EmployeeProfile", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.LostAndFoundItem", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.EmployeeProfile", "FoundByEmployee")
                        .WithMany()
                        .HasForeignKey("FoundByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Room", "Room")
                        .WithMany("FoundItems")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoundByEmployee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.MaintenanceRequest", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Room", "Room")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.HousekeepingMaintenance.RoomCleaning", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.EmployeeProfile", "AssignedEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeId");

                    b.HasOne("HotelSystemIndustry.Models.Room", "Room")
                        .WithMany("Cleanings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Invoice", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Reservation", "Reservation")
                        .WithOne("Invoice")
                        .HasForeignKey("HotelSystemIndustry.Models.Invoice", "ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.ArticleInstance", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Kitchen.KitchenArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Kitchen.Storage", "Storage")
                        .WithMany("Articles")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenArticle", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Kitchen.KitchenArticleType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenProduct", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Events.EventReservation", null)
                        .WithMany("Food")
                        .HasForeignKey("EventReservationId");

                    b.HasOne("HotelSystemIndustry.Models.Kitchen.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenRecipe", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Kitchen.KitchenProduct", "OutcomeProduct")
                        .WithMany()
                        .HasForeignKey("OutcomeProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutcomeProduct");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenRecipeIngredient", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Kitchen.KitchenArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Kitchen.KitchenRecipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.Order", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Kitchen.OrderType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Payment", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Reservation", "Service")
                        .WithOne("Payment")
                        .HasForeignKey("HotelSystemIndustry.Models.Payment", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Phone", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Hotel", "Hotel")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.RaportPayment", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Payment", "Payment")
                        .WithMany("RaportPayments")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Raport", "Raport")
                        .WithMany("RaportPayments")
                        .HasForeignKey("RaportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Raport");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Recreation.RecreationBooking", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Recreation.RecreationFacility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Guest", "Guest")
                        .WithMany("RecreationBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Reservation", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Room", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.Purchase", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Trading.ShopPoint", "ShopPoint")
                        .WithOne("Purchase")
                        .HasForeignKey("HotelSystemIndustry.Models.Trading.Purchase", "ShopPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShopPoint");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.SaleItem", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Trading.SaleItemType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.SaleItemInstance", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.Trading.SaleItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Trading.ShopMagazine", "Magazine")
                        .WithMany("Items")
                        .HasForeignKey("MagazineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.Trading.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Magazine");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("SupplyUsage", b =>
                {
                    b.HasOne("HotelSystemIndustry.Models.HousekeepingMaintenance.RoomCleaning", "RoomCleaning")
                        .WithMany()
                        .HasForeignKey("RoomCleaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystemIndustry.Models.HousekeepingMaintenance.HousekeepingSupply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomCleaning");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventHall", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Events.EventReservation", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Guest", b =>
                {
                    b.Navigation("RecreationBookings");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Hotel", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PhoneNumbers");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.KitchenRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Kitchen.Storage", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Payment", b =>
                {
                    b.Navigation("RaportPayments");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Raport", b =>
                {
                    b.Navigation("RaportPayments");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Recreation.RecreationFacility", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Reservation", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Room", b =>
                {
                    b.Navigation("Cleanings");

                    b.Navigation("FoundItems");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.ShopMagazine", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HotelSystemIndustry.Models.Trading.ShopPoint", b =>
                {
                    b.Navigation("Purchase");
                });
#pragma warning restore 612, 618
        }
    }
}
